version: "3.9"

services:
  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - nephro-net

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    networks:
      - nephro-net


  frontend-angular:
    build: ./frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - api-gateway
    networks:
      - nephro-net

networks:
  nephro-net:
    driver: bridge
